@endpoint = https://g0djw4hhyj.execute-api.us-east-1.amazonaws.com/prod/

GET {{endpoint}}/hello
###

GET {{endpoint}}/spaces?spaceId=5571c78e-c888-4805-bb09-607b55d7d09c
###

POST {{endpoint}}/spaces
Content-Type: application/json

{
    "location": "San Antonio",
    "name": "River Walk"
}
###
